export const CAR_SEARCH_API_URL = 'https://marketcheck-prod.apigee.net/v1/search?';
export const CAR_SEARCH_API_KEY = 'api_key=CpV8TN8VsKdYJMDWG7o5gBm5js1017nv&';
export const carSuggestions = [
  { label: 'Alfa Romeo' },
  { label: 'Aston Martin' },
  { label: 'Audi' },
  { label: 'Bentley' },
  { label: 'Benz' },
  { label: 'BMW' },
  { label: 'Bugatti' },
  { label: 'Cadillac' },
  { label: 'Chevrolet' },
  { label: 'Chrysler' },
  { label: 'Citroen' },
  { label: 'Corvette' },
  { label: ' DAF' },
  { label: ' Dacia' },
  { label: ' Daewoo' },
  { label: ' Daihatsu' },
  { label: 'Datsun' },
  { label: ' De Lorean' },
  { label: ' Dino' },
  { label: ' Dodge' },
  { label: 'Farboud' },
  { label: 'Ferrari' },
  { label: 'Fiat' },
  { label: 'Ford' },
  { label: 'Honda' },
  { label: 'Hummer' },
  { label: 'Hyundai' },
  { label: ' Jaguar' },
  { label: 'Jeep' },
  { label: ' KIA' },
  { label: 'Koenigsegg' },
  { label: 'Lada' },
  { label: 'Lamborghini' },
  { label: ' Lancia' },
  { label: ' Land Rover' },
  { label: ' Lexus' },
  { label: ' Ligier' },
  { label: ' Lincoln' },
  { label: ' Lotus' },
  { label: ' Martini' },
  { label: ' Maserati' },
  { label: ' Maybach' },
  { label: ' Mazda' },
  { label: ' McLaren' },
  { label: ' Mercedes' },
  { label: ' Mercedes-Benz' },
  { label: ' Mini' },
  { label: ' Mitsubishi' },
  { label: 'Nissan' },
  { label: 'Noble' },
  { label: 'Opel' },
  { label: 'Peugeot' },
  { label: 'Pontiac' },
  { label: 'Porsche' },
  { label: 'Renault' },
  { label: 'Rolls-Royce' },
  { label: 'Rover' },
  { label: 'Saab' },
  { label: 'Seat' },
  { label: 'Skoda' },
  { label: 'Smart' },
  { label: 'Spyker' },
  { label: 'Subaru' },
  { label: 'Suzuki' },
  { label: 'Toyota' },
  { label: 'Vauxhall' },
  { label: 'Volkswagen' },
  { label: ' Volvo' },
];